### PR TITLE
Banner

### PR DESCRIPTION
**Pull request by FilipeDias23**
Just finished the banner, tell me if i need to change something ! Hope you like it

### CODE REVIEW

**Comment by FilipeDias23** [comment]
it says that the branch has conflits but its the import scss files only.. dont know why..

**Comment by FilipeDias23** [comment]
I also did the Collection cards aswell on this branch .

**Comment by ClaudiaTr** [comment]
> it says that the branch has conflits but its the import scss files only.. dont know why..

it is because I also changed things in application.scss. if you read the code, you just added something and I removed something. I actually just found out, that in application.scss you don't need to import anything. you have an extra partial called _index.scss. there you can link your components. but you can do this later. for now it's ok to remove the conflict markers

**Comment by FilipeDias23** [comment]
yes probably, I tought it too ,  we can change later .

**Pull request merged**
